In [2]:
import pandas as pd 
df=pd.read_csv(r'C:\Users\ADMIN\Downloads\archive\swiggy.csv')
df.head()

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8680 entries, 0 to 8679
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             8680 non-null   int64
 1   Area           8680 non-null   object
 2   City           8680 non-null   object
 3   Restaurant     8680 non-null   object
 4   Price          8680 non-null   float64
 5   Avg ratings    8680 non-null   float64
 6   Total ratings  8680 non-null   int64
 7   Food type      8680 non-null   object
 8   Address        8680 non-null   object
 9   Delivery time  8680 non-null   int64
dtypes: float64(2), int64(3), object(5)
memory usage: 678.3+ KB

In [4]:
df.describe()

                  ID        Price  Avg ratings  Total ratings  Delivery time
count    8680.000000  8680.000000  8680.000000    8680.000000    8680.000000
mean   244812.071429   348.444470     3.655104     156.634793      53.967051
std    158671.617188   230.940074     0.647629     391.448014      14.292335
min       211.000000     0.000000     2.000000      20.000000      20.000000
25%     72664.000000   200.000000     2.900000      50.000000      44.000000
50%    283442.000000   300.000000     3.900000      80.000000      53.000000
75%    393425.250000   400.000000     4.200000     100.000000      64.000000
max    466928.000000  2500.000000     5.000000   10000.000000     109.000000

In [5]:
df.shape

(8680, 10)

In [6]:
df.columns

Index(['ID', 'Area', 'City', 'Restaurant', 'Price', 'Avg ratings',
       'Total ratings', 'Food type', 'Address', 'Delivery time'],
      dtype='object')

In [7]:
df.columns=df.columns.str.lower().str.replace(" ","_")

In [8]:
df.columns

Index(['id', 'area', 'city', 'restaurant', 'price', 'avg_ratings',
       'total_ratings', 'food_type', 'address', 'delivery_time'],
      dtype='object')

In [9]:
df.isnull().sum()

id               0
area             0
city             0
restaurant       0
price            0
avg_ratings      0
total_ratings    0
food_type        0
address          0
delivery_time    0
dtype: int64

In [10]:
df=df.drop_duplicates()

In [11]:
df['total_ratings']=pd.to_numeric(df['total_ratings'],errors='coerce')

In [12]:
df.isnull().sum()

id               0
area             0
city             0
restaurant       0
price            0
avg_ratings      0
total_ratings    0
food_type        0
address          0
delivery_time    0
dtype: int64

In [13]:
df['price']=df['price'].astype(str).str.replace('₹','')

In [14]:
df['price']=pd.to_numeric(df['price'] , errors='coerce')

In [15]:
df.isnull().sum()

id               0
area             0
city             0
restaurant       0
price            0
avg_ratings      0
total_ratings    0
food_type        0
address          0
delivery_time    0
dtype: int64

In [16]:
df['restaurant']=df['restaurant'].str.strip()
df['city']=df['city'].str.strip()

In [17]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8680 entries, 0 to 8679
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             8680 non-null   int64
 1   area           8680 non-null   object
 2   city           8680 non-null   object
 3   restaurant     8680 non-null   object
 4   price          8680 non-null   float64
 5   avg_ratings    8680 non-null   float64
 6   total_ratings  8680 non-null   int64
 7   food_type      8680 non-null   object
 8   address        8680 non-null   object
 9   delivery_time  8680 non-null   int64
dtypes: float64(2), int64(3), object(5)
memory usage: 678.3+ KB

id               0
area             0
city             0
restaurant       0
price            0
avg_ratings      0
total_ratings    0
food_type        0
address          0
delivery_time    0
dtype: int64

In [18]:
df['food_type'] = df['food_type'].str.split(',')

In [19]:
df = df.explode('food_type')

In [20]:
df['food_type'] = df['food_type'].str.strip()

In [21]:
df['food_type'] = df['food_type'].str.title()

In [22]:
df.head()

,id,area,city,restaurant,price,avg_ratings,total_ratings,food_type,address,delivery_time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,Biryani,5Th Block,59
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,Chinese,5Th Block,59
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,North Indian,5Th Block,59
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,South Indian,5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,Mughlai,5Th Block,56

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23623 entries, 0 to 8679
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             23623 non-null  int64
 1   area           23623 non-null  object
 2   city           23623 non-null  object
 3   restaurant     23623 non-null  object
 4   price          23623 non-null  float64
 5   avg_ratings    23623 non-null  float64
 6   total_ratings  23623 non-null  int64
 7   food_type      23623 non-null  object
 8   address        23623 non-null  object
 9   delivery_time  23623 non-null  int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.0+ MB

In [32]:
df_main=df.drop(columns=['food_type']).drop_duplicates()

In [33]:
food_df=df[['id','food_type']]

In [34]:
food_df.head()

    id     food_type
0  211       Biryani
0  211       Chinese
0  211  North Indian
0  211  South Indian
1  221       Mughlai

In [35]:
food_df=food_df.drop_duplicates()

In [40]:
df_main.shape

(8680, 9)

In [42]:
food_df.shape

(23621, 2)

In [43]:
df_main.to_csv('clean_swiggy.csv',index=False)
food_df.to_csv('food_data.csv',index=False)